#
# Linux Support for 64bit Amlogic Meson SoCs
#

FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}-${PV}:"

SRCREV_meson = "c3915fe1bf1235dbf3b0bced734c960202915bd5"
LINUX_VERSION = "5.2.11"
	
# Linux stable tree
SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git;protocol=https;branch=linux-5.2.y;name=meson \
           file://defconfig \
           file://0001-UPSTREAM-ASoC-hdmi-codec-remove-function-name-debug-.patch \
           file://0002-UPSTREAM-ASoC-hdmi-codec-remove-reference-to-the-cur.patch \
           file://0003-UPSTREAM-ASoC-hdmi-codec-remove-reference-to-the-dai.patch \
           file://0004-UPSTREAM-ASoC-hdmi-codec-remove-ops-dependency-on-th.patch \
           file://0005-UPSTREAM-ASoC-meson-axg-card-set-link-name-based-on-.patch \
           file://0006-UPSTREAM-ASoC-dapm-allow-muxes-to-force-a-disconnect.patch \
           file://0007-UPSTREAM-ASoC-meson-add-tohdmitx-DT-bindings.patch \
           file://0008-UPSTREAM-ASoC-meson-axg-card-add-basic-codec-to-code.patch \
           file://0009-UPSTREAM-ASoC-meson-add-g12a-tohdmitx-control.patch \
           file://0010-UPSTREAM-clk-meson-gxbb-no-spread-spectrum-on-mpll0.patch \
           file://0011-UPSTREAM-clk-meson-axg-spread-spectrum-is-on-mpll2.patch \
           file://0012-UPSTREAM-clk-meson-mpll-add-init-callback-and-regs.patch \
           file://0013-UPSTREAM-clk-meson-g12a-add-mpll-register-init-seque.patch \
           file://0014-UPSTREAM-clk-meson-eeclk-add-init-regs.patch \
           file://0015-UPSTREAM-clk-meson-g12a-add-controller-register-init.patch \
           file://0016-UPSTREAM-arm64-dts-meson-g12a-Add-PWM-nodes.patch \
           file://0017-UPSTREAM-arm64-dts-meson-g12a-Add-IR-nodes.patch \
           file://0018-UPSTREAM-arm64-dts-meson-g12a-x96-max-enable-IR-deco.patch \
           file://0019-UPSTREAM-arm64-dts-meson-g12a-u200-enable-IR-decoder.patch \
           file://0020-UPSTREAM-arm64-dts-meson-sei510-consistently-order-n.patch \
           file://0021-UPSTREAM-arm64-dts-meson-u200-consistently-order-nod.patch \
           file://0022-UPSTREAM-arm64-dts-meson-g12a-add-mmc-nodes.patch \
           file://0023-UPSTREAM-arm64-dts-meson-u200-add-sd-and-emmc.patch \
           file://0024-UPSTREAM-arm64-dts-meson-sei510-add-sd-and-emmc.patch \
           file://0025-UPSTREAM-arm64-dts-meson-g12a-set-uart_ao-clocks.patch \
           file://0026-UPSTREAM-arm64-dts-meson-g12a-add-i2c-nodes.patch \
           file://0027-UPSTREAM-arm64-dts-meson-u200-enable-i2c-busses.patch \
           file://0028-UPSTREAM-arm64-dts-meson-sei510-enable-i2c3.patch \
           file://0029-UPSTREAM-arm64-dts-meson-g12a-add-audio-clock-contro.patch \
           file://0030-UPSTREAM-arm64-dts-meson-g12a-add-audio-memory-arbit.patch \
           file://0031-UPSTREAM-arm64-dts-meson-g12a-add-audio-fifos.patch \
           file://0032-UPSTREAM-arm64-dts-meson-g12a-add-tdm.patch \
           file://0033-UPSTREAM-arm64-dts-meson-g12a-add-spdifouts.patch \
           file://0034-UPSTREAM-arm64-dts-meson-g12a-add-pdm.patch \
           file://0035-UPSTREAM-arm64-dts-meson-g12a-add-spdifin.patch \
           file://0036-UPSTREAM-arm64-dts-meson-g12a-enable-hdmi_tx-sound-d.patch \
           file://0037-UPSTREAM-dt-bindings-arm-amlogic-Move-amlogic-meson-.patch \
           file://0038-UPSTREAM-dt-bindings-arm-Convert-Amlogic-board-soc-b.patch \
           file://0039-UPSTREAM-arm64-dts-meson-sei510-add-bluetooth-suppli.patch \
           file://0040-UPSTREAM-arm64-dts-meson-g12a-add-tohdmitx.patch \
           file://0041-UPSTREAM-arm64-dts-meson-g12a-add-ethernet-mac-contr.patch \
           file://0042-FROMGIT-arm64-dts-meson-g12a-add-ethernet-pinctrl-de.patch \
           file://0043-FROMGIT-arm64-dts-meson-g12a-add-mdio-multiplexer.patch \
           file://0044-FROMGIT-arm64-dts-meson-u200-add-internal-network.patch \
           file://0045-FROMGIT-arm64-dts-meson-sei510-add-network-support.patch \
           file://0046-FROMGIT-arm64-dts-meson-g12a-add-drive-strength-hdmi.patch \
           file://0047-FROMGIT-arm64-dts-meson-g12a-add-drive-strength-for-.patch \
           file://0048-FROMGIT-dt-bindings-mmc-meson-gx-add-dram-access-qui.patch \
           file://0049-FROMGIT-mmc-meson-gx-add-dram-access-quirk.patch \
           file://0050-UPSTREAM-dt-bindings-pinctrl-add-a-drive-strength-mi.patch \
           file://0051-UPSTREAM-pinctrl-generic-add-new-drive-strength-micr.patch \
           file://0052-UPSTREAM-dt-bindings-pinctrl-meson-Add-drive-strengt.patch \
           file://0053-UPSTREAM-pinctrl-meson-Rework-enable-disable-bias-pa.patch \
           file://0054-UPSTREAM-pinctrl-meson-add-support-of-drive-strength.patch \
           file://0055-UPSTREAM-pinctrl-meson-g12a-add-DS-bank-value.patch \
           file://0056-UPSTREAM-dt-bindings-pinctrl-meson-add-output-suppor.patch \
           file://0057-UPSTREAM-pinctrl-meson-add-output-support-in-pinconf.patch \
           file://0058-UPSTREAM-drm-meson-imply-dw-hdmi-i2s-audio-for-meson.patch \
           file://0059-FROMGIT-arm64-dts-meson-g12a-Add-hwrng-node.patch \
           file://0060-FROMGIT-arm64-dts-meson-g12a-x96-max-Add-Gigabit-Eth.patch \
           file://0061-FROMGIT-dt-bindings-arm-amlogic-add-G12B-bindings.patch \
           file://0062-FROMGIT-dt-bindings-arm-amlogic-add-Odroid-N2-bindin.patch \
           file://0063-FROMGIT-arm64-dts-meson-Add-minimal-support-for-Odro.patch \
           file://0064-UPSTREAM-media-platform-ao-cec-g12a-remove-spin_lock.patch \
           file://0065-UPSTREAM-drm-meson-Add-zpos-immutable-property-to-pl.patch \
           file://0066-UPSTREAM-drm-meson-Add-support-for-XBGR8888-ABGR8888.patch \
           file://0067-FROMGIT-arm64-dts-meson-g12a-add-SDIO-controller.patch \
           file://0068-FROMGIT-arm64-dts-meson-g12a-x96-max-add-support-for.patch \
           file://0069-FROMGIT-arm64-dts-meson-g12a-x96-max-Enable-Wifi-SDI.patch \
           file://0070-FROMGIT-arm64-dts-meson-g12a-sei510-Enable-Wifi-SDIO.patch \
           file://0071-FROMGIT-arm64-dts-meson-g12a-sei510-add-32k-clock-to.patch \
           file://0072-FROMGIT-arm64-dts-meson-g12a-x96-max-add-32k-clock-t.patch \
           file://0073-FROMGIT-arm64-dts-meson-g12a-sei510-bump-bluetooth-b.patch \
           file://0074-FROMGIT-arm64-dts-meson-g12a-x96-max-bump-bluetooth-.patch \
           file://0075-UPSTREAM-dt-bindings-clk-g12a-clkc-add-Temperature-S.patch \
           file://0076-UPSTREAM-clk-meson-g12a-add-temperature-sensor-clock.patch \
           file://0077-UPSTREAM-dt-bindings-clk-meson-add-g12b-periph-clock.patch \
           file://0078-UPSTREAM-clk-meson-g12a-Add-support-for-G12B-CPUB-cl.patch \
           file://0079-UPSTREAM-clk-meson-g12a-mark-fclk_div3-as-critical.patch \
           file://0080-FROMGIT-drm-bridge-dw-hdmi-Use-automatic-CTS-generat.patch \
           file://0081-FROMGIT-arm64-dts-amlogic-odroid-n2-keep-SD-card-reg.patch \
           file://0082-FROMGIT-arm64-dts-meson-g12a-add-missing-dwc2-phy-na.patch \
           file://0083-FROMGIT-arm64-dts-meson-g12a-sei510-enable-IR-contro.patch \
           file://0084-FROMGIT-clk-meson-g12a-fix-hifi-typo-in-mali-parent_.patch \
           file://0085-FROMGIT-clk-meson-axg-audio-migrate-to-the-new-paren.patch \
           file://0086-FROMGIT-clk-meson-g12a-aoclk-migrate-to-the-new-pare.patch \
           file://0087-FROMGIT-clk-meson-gxbb-aoclk-migrate-to-the-new-pare.patch \
           file://0088-FROMGIT-clk-meson-axg-aoclk-migrate-to-the-new-paren.patch \
           file://0089-FROMGIT-clk-meson-remove-ao-input-bypass-clocks.patch \
           file://0090-FROMGIT-clk-meson-g12a-migrate-to-the-new-parent-des.patch \
           file://0091-FROMGIT-clk-meson-gxbb-migrate-to-the-new-parent-des.patch \
           file://0092-FROMGIT-clk-meson-axg-migrate-to-the-new-parent-desc.patch \
           file://0093-BACKPORT-clk-meson-meson8b-migrate-to-the-new-parent.patch \
           file://0094-BACKPORT-clk-meson-clk-regmap-migrate-to-new-parent-.patch \
           file://0095-FROMGIT-clk-meson-remove-ee-input-bypass-clocks.patch \
           file://0096-BACKPORT-clk-meson-remove-clk-input-helper.patch \
           file://0097-UPSTREAM-pwm-meson-Fix-the-G12A-AO-clock-parents-ord.patch \
           file://0098-UPSTREAM-pwm-meson-Unify-the-parameter-list-of-meson.patch \
           file://0099-UPSTREAM-pwm-meson-Use-devm_clk_get_optional-to-get-.patch \
           file://0100-UPSTREAM-pwm-meson-Use-GENMASK-and-FIELD_PREP-for-th.patch \
           file://0101-UPSTREAM-pwm-meson-Change-MISC_CLK_SEL_WIDTH-to-MISC.patch \
           file://0102-UPSTREAM-pwm-meson-Don-t-duplicate-the-polarity-inte.patch \
           file://0103-UPSTREAM-pwm-meson-Pass-struct-pwm_device-to-meson_p.patch \
           file://0104-UPSTREAM-pwm-meson-Add-the-meson_pwm_channel-data-to.patch \
           file://0105-UPSTREAM-pwm-meson-Add-the-per-channel-register-offs.patch \
           file://0106-UPSTREAM-pwm-meson-Move-pwm_set_chip_data-to-meson_p.patch \
           file://0107-UPSTREAM-pwm-meson-Simplify-the-calculation-of-the-p.patch \
           file://0108-UPSTREAM-pwm-meson-Read-the-full-hardware-state-in-m.patch \
           file://0109-UPSTREAM-pwm-meson-Don-t-cache-struct-pwm_state-inte.patch \
           file://0110-UPSTREAM-pwm-meson-Add-support-PWM_POLARITY_INVERSED.patch \
           file://0111-FROMGIT-clk-core-introduce-clk_hw_set_parent.patch \
           file://0112-FROMGIT-clk-meson-add-g12a-cpu-dynamic-divider-drive.patch \
           file://0113-FROMGIT-clk-meson-g12a-add-notifiers-to-handle-cpu-c.patch \
           file://0114-FROMGIT-clk-meson-g12a-expose-CPUB-clock-ID-for-G12B.patch \
           file://0115-FROMGIT-soc-amlogic-meson-clk-measure-protect-measur.patch \
           file://0116-FROMGIT-soc-amlogic-meson-clk-measure-add-G12B-secon.patch \
           file://0117-FROMGIT-soc-amlogic-meson-gx-socinfo-add-A311D-id.patch \
           file://0118-BACKPORT-arm64-dts-move-common-G12A-G12B-modes-to-me.patch \
           file://0119-FROMGIT-arm64-dts-meson-g12-common-add-pwm_a-on-GPIO.patch \
           file://0120-FROMGIT-arm64-dts-meson-g12a-add-cpus-OPP-table.patch \
           file://0121-BACKPORT-arm64-dts-meson-g12a-enable-DVFS-on-G12A-bo.patch \
           file://0122-FROMGIT-arm64-dts-meson-g12b-add-cpus-OPP-tables.patch \
           file://0123-FROMGIT-arm64-dts-meson-add-ethernet-fifo-sizes.patch \
           file://0124-FROMGIT-dt-bindings-arm-amlogic-add-bindings-for-G12.patch \
           file://0125-FROMGIT-dt-bindings-arm-amlogic-add-bindings-for-the.patch \
           file://0126-FROMGIT-dt-bindings-arm-amlogic-add-support-for-the-.patch \
           file://0127-FROMGIT-arm64-dts-meson-g12b-support-a311d-and-s922x.patch \
           file://0128-FROMGIT-pinctrl-meson-g12a-add-pwm_a-on-GPIOE_2-pinm.patch \
           file://0129-FROMGIT-media-dt-bindings-media-meson-ao-cec-add-SM1.patch \
           file://0130-FROMGIT-media-platform-meson-ao-cec-g12a-add-support.patch \
           file://0131-BACKPORT-ASoC-add-soc-dai.c.patch \
           file://0132-BACKPORT-ASoC-soc-dai-mv-soc_dai_hw_params-to-soc-da.patch \
           file://0133-BACKPORT-ASoC-soc-dai-add-snd_soc_dai_hw_free.patch \
           file://0134-BACKPORT-ASoC-soc-dai-add-snd_soc_dai_startup.patch \
           file://0135-BACKPORT-ASoC-soc-dai-add-snd_soc_dai_shutdown.patch \
           file://0136-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_prepare.patch \
           file://0137-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_trigger.patch \
           file://0138-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_bespoke_trigger.patch \
           file://0139-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_delay.patch \
           file://0140-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_suspend.patch \
           file://0141-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_resume.patch \
           file://0142-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_probe.patch \
           file://0143-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_remove.patch \
           file://0144-FROMGIT-ASoC-soc-dai-add-snd_soc_dai_compress_new.patch \
           file://0145-FROMGIT-ASoC-soc-dai-move-snd_soc_dai_stream_valid-t.patch \
           file://0146-FROMGIT-ASoC-codec2codec-run-callbacks-in-order.patch \
           file://0147-FROMGIT-ASoC-codec2codec-name-link-using-stream-dire.patch \
           file://0148-FROMGIT-ASoC-codec2codec-deal-with-params-when-neces.patch \
           file://0149-FROMGIT-ASoC-meson-g12a-tohdmitx-override-codec2code.patch \
           file://0150-FROMGIT-ASoC-create-pcm-for-codec2codec-links-as-wel.patch \
           file://0151-FROMGIT-ASoC-codec2codec-fix-missing-return-of-error.patch \
           file://0152-FROMGIT-ASoC-codec2codec-remove-ephemeral-variables.patch \
           file://0153-FROMGIT-ASoC-codec2codec-fill-some-of-the-runtime-st.patch \
           file://0154-FROMGIT-drm-meson-mask-value-when-writing-bits-relax.patch \
           file://0155-FROMGIT-drm-meson-crtc-use-proper-macros-instead-of-.patch \
           file://0156-FROMGIT-drm-meson-drv-use-macro-when-initializing-vp.patch \
           file://0157-FROMGIT-drm-meson-vpp-use-proper-macros-instead-of-m.patch \
           file://0158-FROMGIT-drm-meson-viu-use-proper-macros-instead-of-m.patch \
           file://0159-FROMGIT-drm-meson-venc-use-proper-macros-instead-of-.patch \
           file://0160-FROMGIT-drm-meson-global-clean-up.patch \
           file://0161-FROMGIT-drm-meson-add-macro-used-to-enable-HDMI-PLL.patch \
           file://0162-FROMGIT-drm-meson-venc-set-the-correct-macrovision-m.patch \
           file://0163-FROMGIT-arm64-dts-amlogic-g12-CPU-timers-stop-in-sus.patch \
           file://0164-FROMGIT-dt-bindings-arm-amlogic-fix-x96-max-sei510-s.patch \
           file://0165-BACKPORT-arm64-dts-meson-g12b-khadas-vim3-add-initia.patch \
           file://0166-BACKPORT-arm64-dts-meson-g12b-odroid-n2-enable-DVFS.patch \
           file://0167-FROMLIST-clk-meson-g12a-fix-gp0-and-hifi-ranges.patch \
           file://0168-FROMLIST-dt-bindings-thermal-Add-DT-bindings-documen.patch \
           file://0169-FROMLIST-thermal-amlogic-Add-thermal-driver-to-suppo.patch \
           file://0170-FROMLIST-arm64-dts-amlogic-g12-add-temperature-senso.patch \
           file://0171-BACKPORT-arm64-dts-meson-sei510-Add-minimal-thermal-.patch \
           file://0172-BACKPORT-arm64-dts-amlogic-odroid-n2-add-minimal-the.patch \
           file://0173-FROMLIST-MAINTAINERS-add-entry-for-Amlogic-Thermal-d.patch \
           file://0174-FROMLIST-drm-bridge-dw-hdmi-i2s-support-more-i2s-for.patch \
           file://0175-FROMLIST-drm-bridge-dw-hdmi-move-audio-channel-setup.patch \
           file://0176-FROMLIST-drm-bridge-dw-hdmi-set-channel-count-in-the.patch \
           file://0177-FROMLIST-drm-bridge-dw-hdmi-i2s-enable-lpcm-multi-ch.patch \
           file://0178-FROMLIST-drm-bridge-dw-hdmi-i2s-set-the-channel-allo.patch \
           file://0179-FROMLIST-drm-bridge-dw-hdmi-i2s-reset-audio-fifo-bef.patch \
           file://0180-FROMLIST-drm-bridge-dw-hdmi-i2s-enable-only-the-requ.patch \
           file://0181-FROMLIST-drm-bridge-dw-hdmi-i2s-add-.get_eld-support.patch \
           file://0182-FROMLIST-dt-bindings-clock-meson-add-resets-to-the-a.patch \
           file://0183-FROMLIST-clk-meson-axg-audio-add-g12a-reset-support.patch \
           file://0184-FROMLIST-arm64-cpufeature-Don-t-treat-granule-sizes-.patch \
           file://0185-FROMLIST-arm64-dts-meson-sei510-add-max98357a-DAC.patch \
           file://0186-BACKPORT-arm64-dts-meson-sei510-add-sound-card.patch \
           file://0187-FROMLIST-arm64-dts-meson-g12a-x96-max-add-sound-card.patch \
           file://0188-FROMLIST-arm64-dts-meson-g12b-odroid-n2-add-sound-ca.patch \
           file://0189-FROMLIST-usb-dwc3-meson-g12a-Add-support-for-IRQ-bas.patch \
           file://0190-FROMLIST-Bluetooth-btbcm-Add-entry-for-BCM4359C0-UAR.patch \
           file://0191-WIP-ASoC-max98357a-add-Kconfig-name.patch \
           file://0192-WIP-ASoC-hdmi-codec-re-introduce-mutex-locking.patch \
           file://0193-WIP-arm64-dts-meson-add-dwmac-3.710-to-ethmac-compat.patch \
           file://0194-WIP-drm-bridge-dw-hdmi-support-dynamically-get-input.patch \
           file://0195-WIP-drm-bridge-dw-hdmi-allow-ycbcr420-modes-for-0x20.patch \
           file://0196-WIP-drm-meson-Add-YUV420-output-support.patch \
           file://0197-WIP-drm-meson-Output-in-YUV444-if-sink-supports-it.patch \
           file://0198-WIP-dt-bindings-media-add-Amlogic-Video-Decoder-Bind.patch \
           file://0199-WIP-media-videodev2-add-V4L2_FMT_FLAG_FIXED_RESOLUTI.patch \
           file://0200-WIP-media-meson-add-v4l2-m2m-video-decoder-driver.patch \
           file://0201-WIP-MAINTAINERS-Add-meson-video-decoder.patch \
           file://0202-WIP-arm64-dts-meson-gx-add-vdec-entry.patch \
           file://0203-WIP-arm64-dts-meson-add-vdec-entries.patch \
           file://0204-WIP-media-meson-vdec-add-H.264-decoding-support.patch \
           file://0205-WIP-media-meson-vdec-add-MPEG4-decoding-support.patch \
           file://0206-WIP-media-meson-vdec-add-MJPEG-decoding-support.patch \
           file://0207-WIP-media-videodev2.h-Add-Amlogic-compressed-format.patch \
           file://0208-WIP-media-meson-vdec-add-support-for-V4L2_PIX_FMT_AM.patch \
           file://0209-WIP-meson-vdec-make-amvdec_dst_buf_done_offset-publi.patch \
           file://0210-WIP-media-meson-vdec-add-HEVC-decoding-support.patch \
           file://0211-WIP-meson-vdec-Map-the-Firmware-buf-idx-VB2-buf-idx.patch \
           file://0212-WIP-media-meson-vdec-commonize-some-HEVC-code.patch \
           file://0213-WIP-media-meson-vdec-add-VP9-input-support.patch \
           file://0214-WIP-media-meson-vdec-add-VP9-support.patch \
           file://0215-WIP-media-meson-vdec-add-g12a-platform.patch \
           file://0216-WIP-media-meson-vp9-add-IOMMU-support.patch \
           file://0217-WIP-arm64-dts-meson-g12a-add-video-decoder-node.patch \
           file://0218-HACK-arm64-dts-g12a-set-cma-pool-to-896MB.patch \
           file://0219-ARM64-defconfig-enable-CEC-support.patch \
           file://0220-ASoC-meson-add-meson-audio-core-driver.patch \
           file://0221-ASoC-meson-add-register-definitions.patch \
           file://0222-ASoC-meson-add-initial-aiu-i2s-support.patch \
           file://0223-ASoC-meson-add-initial-spdif-support.patch \
           file://0224-ARM64-defconfig-enable-audio-support-for-meson-SoCs-.patch \
           file://0225-ARM64-dts-meson-gx-add-audio-controller-nodes.patch \
           file://0226-snd-meson-activate-HDMI-audio-path.patch \
           file://0227-ARM64-dts-meson-gx-add-sound-dai-cells-to-HDMI-node.patch \
           file://0228-ARM64-dts-meson-activate-hdmi-audio-HDMI-enabled-boa.patch \
           file://0229-arm64-dts-meson-gxm-nexbox-a1-disable-cvbs.patch \
           file://0230-WiP-drm-panfrost-add-support-for-custom-soft-reset-o.patch \
           file://0231-TEMP-drm-panfrost-kernel-driver-fix-1-2.patch \
           file://0232-TEMP-drm-panfrost-kernel-driver-fix-2-2.patch \
           file://0001-clk-Fix-potential-NULL-dereference-in-clk_fetch_pare.patch \
           "

KERNEL_VERSION_SANITY_SKIP="1"

KERNEL_CLASSES = "kernel-uimage-meson"

LINUX_VERSION_EXTENSION_append = "-meson64"

KERNEL_CONFIG_COMMAND ?= "oe_runmake_call -C ${S} CC="${KERNEL_CC}" O=${B} olddefconfig"

require linux-meson.inc

# Checksum changed on 4.17
LIC_FILES_CHKSUM = "file://COPYING;md5=bbea815ee2795b2f4230826c0c6b8814"

